# Generated by Django 4.1.2 on 2022-11-16 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('height_inches', models.IntegerField(default=0)),
                ('weight_lbs', models.IntegerField(default=0)),
                ('birth_date', models.DateField()),
                ('gender', models.CharField(max_length=1)),
                ('bench_max_lbs', models.IntegerField(default=0)),
                ('squat_max_lbs', models.IntegerField(default=0)),
                ('mile_time_sec', models.IntegerField(default=0)),
            ],
        ),
    ]
